
UPDATE public.produits SET isbn = NULL WHERE isbn = 'N/A';

WITH data(ref, niveau, matiere, categorie) AS (
  VALUES
    ('PRD00001','CP1','Français','Maternelle / Primaire'),
    ('PRD00002','CP1','Français','Maternelle / Primaire'),
    ('PRD00003','CP2','Français','Maternelle / Primaire'),
    ('PRD00004','CE1','Français','Maternelle / Primaire'),
    ('PRD00005','CE2','Français','Maternelle / Primaire'),
    ('PRD00006','CM1','Français','Maternelle / Primaire'),
    ('PRD00007','CM2','Français','Maternelle / Primaire'),
    ('PRD00008','CM1','Toutes matières','Maternelle / Primaire'),
    ('PRD00009','CM1','Toutes matières','Maternelle / Primaire'),
    ('PRD00010','CEPE','Toutes matières','Maternelle / Primaire'),
    ('PRD00011','CEPE','Toutes matières','Maternelle / Primaire'),
    ('PRD00012','6E','Mathématiques','Maternelle / Primaire'),
    ('PRD00013','6E','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00014','5E','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00015','6E','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00016','5E','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00017','4E','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00018','3E','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00019','6E','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00020','6E','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00021','5E','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00022','4E','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00023','3E','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00024','2NDE','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00025','1ERE','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00026','Tous niveaux','Éducation Musicale','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00027','6E à Terminale','Arts Plastiques','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00028','5E','Arts Plastiques','Premier cycle - Éducation Musicale / Arts'),
    ('PRD00029','BEPC','Mathématiques','Second cycle - Mémos et Tests BEPC'),
    ('PRD00030','BEPC','Physique-Chimie','Second cycle - Mémos et Tests BEPC'),
    ('PRD00031','BEPC','Français','Second cycle - Mémos et Tests BEPC'),
    ('PRD00032','BEPC','SVT','Second cycle - Mémos et Tests BEPC'),
    ('PRD00033','BEPC','Histoire-Géographie','Second cycle - Mémos et Tests BEPC'),
    ('PRD00034','BEPC','Physique-Chimie','Second cycle - Mémos et Tests BEPC'),
    ('PRD00035','BEPC','SVT','Second cycle - Mémos et Tests BEPC'),
    ('PRD00036','BEPC','Français','Second cycle - Mémos et Tests BEPC'),
    ('PRD00037','BEPC','Histoire-Géographie','Second cycle - Mémos et Tests BEPC'),
    ('PRD00038','BEPC','Anglais','Second cycle - Mémos et Tests BEPC'),
    ('PRD00039','BEPC','Anglais','Second cycle - Mémos et Tests BEPC'),
    ('PRD00040','BAC','Mathématiques','Second cycle - Mémos et Tests BAC'),
    ('PRD00041','BAC','Physique-Chimie','Second cycle - Mémos et Tests BAC'),
    ('PRD00042','BAC','Philosophie','Second cycle - Mémos et Tests BAC'),
    ('PRD00043','BAC','Histoire-Géographie','Second cycle - Mémos et Tests BAC'),
    ('PRD00044','BAC','SVT','Second cycle - Mémos et Tests BAC'),
    ('PRD00045','BAC','Français','Second cycle - Mémos et Tests BAC'),
    ('PRD00046','BAC','Français','Second cycle - Mémos et Tests BAC'),
    ('PRD00047','BAC','Philosophie','Second cycle - Mémos et Tests BAC'),
    ('PRD00048','BAC','SVT','Second cycle - Mémos et Tests BAC'),
    ('PRD00049','BAC','Physique-Chimie','Second cycle - Mémos et Tests BAC'),
    ('PRD00050','BAC','Anglais','Second cycle - Mémos et Tests BAC'),
    ('PRD00051','1ERE','Philosophie','Second cycle - Mémos et Tests BAC'),
    ('PRD00052','TLE','Philosophie','Second cycle - Mémos et Tests BAC'),
    ('PRD00053','Tous publics','Littérature','Littérature / Romans'),
    ('PRD00054','Tous publics','Littérature','Littérature / Romans'),
    ('PRD00055','Tous publics','Littérature','Littérature / Romans'),
    ('PRD00056','Tous publics','Littérature','Littérature / Romans')
)
UPDATE public.produits p
SET niveau = d.niveau,
    matiere = d.matiere,
    categorie = d.categorie,
    updated_at = now()
FROM data d
WHERE p.reference = d.ref;
