
-- Phase 1: Audit journal enterprise foundations

-- 1. Criticality enum + extension of audit_events with location/device/severity
DO $$ BEGIN
  CREATE TYPE public.audit_criticite AS ENUM ('info','warning','critical');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TABLE public.audit_events
  ADD COLUMN IF NOT EXISTS criticite public.audit_criticite NOT NULL DEFAULT 'info',
  ADD COLUMN IF NOT EXISTS city text,
  ADD COLUMN IF NOT EXISTS country text,
  ADD COLUMN IF NOT EXISTS browser text,
  ADD COLUMN IF NOT EXISTS os text,
  ADD COLUMN IF NOT EXISTS device text;

CREATE INDEX IF NOT EXISTS audit_events_criticite_idx ON public.audit_events(criticite);
CREATE INDEX IF NOT EXISTS audit_events_module_action_idx ON public.audit_events(module, action);

-- 2. Immutability: block UPDATE and DELETE at trigger level (belt + suspenders on top of RLS)
CREATE OR REPLACE FUNCTION public.audit_events_block_mutation()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  RAISE EXCEPTION 'audit_events est en lecture seule (%.%)', TG_OP, TG_TABLE_NAME;
END $$;

DROP TRIGGER IF EXISTS trg_audit_events_no_update ON public.audit_events;
CREATE TRIGGER trg_audit_events_no_update
  BEFORE UPDATE OR DELETE ON public.audit_events
  FOR EACH ROW EXECUTE FUNCTION public.audit_events_block_mutation();

-- 3. Security alerts table (auto-generated by detection rules)
CREATE TABLE IF NOT EXISTS public.security_alerts (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  alert_type text NOT NULL,
  criticite public.audit_criticite NOT NULL DEFAULT 'warning',
  user_id uuid,
  user_email text,
  ip_address inet,
  country text,
  city text,
  detail jsonb,
  message text NOT NULL,
  acknowledged_at timestamptz,
  acknowledged_by uuid
);

GRANT SELECT ON public.security_alerts TO authenticated;
GRANT ALL ON public.security_alerts TO service_role;

ALTER TABLE public.security_alerts ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "security_alerts select super admin" ON public.security_alerts;
CREATE POLICY "security_alerts select super admin"
  ON public.security_alerts FOR SELECT
  TO authenticated
  USING (public.has_any_role(auth.uid(), ARRAY['super_admin'::app_role,'directeur_general'::app_role]));

CREATE INDEX IF NOT EXISTS security_alerts_created_idx ON public.security_alerts(created_at DESC);
CREATE INDEX IF NOT EXISTS security_alerts_type_idx ON public.security_alerts(alert_type);

-- 4. RPC: full KPI dashboard in one call
CREATE OR REPLACE FUNCTION public.audit_stats_v2()
RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  WITH e AS (
    SELECT * FROM public.audit_events
    WHERE occurred_at >= now() - interval '90 days'
  )
  SELECT jsonb_build_object(
    'today',              (SELECT count(*) FROM e WHERE occurred_at::date = current_date),
    'week',               (SELECT count(*) FROM e WHERE occurred_at >= date_trunc('week', now())),
    'month',              (SELECT count(*) FROM e WHERE occurred_at >= date_trunc('month', now())),
    'active_users_today', (SELECT count(DISTINCT user_id) FROM e WHERE occurred_at::date = current_date),
    'connected_now',      (SELECT count(DISTINCT user_id) FROM e WHERE occurred_at >= now() - interval '15 minutes'),
    'logins',             (SELECT count(*) FROM e WHERE action = 'LOGIN'),
    'logouts',            (SELECT count(*) FROM e WHERE action = 'LOGOUT'),
    'login_failed',       (SELECT count(*) FROM e WHERE action = 'LOGIN_FAILED'),
    'creations',          (SELECT count(*) FROM e WHERE action = 'INSERT'),
    'modifications',      (SELECT count(*) FROM e WHERE action = 'UPDATE'),
    'suppressions',       (SELECT count(*) FROM e WHERE action = 'DELETE'),
    'impressions',        (SELECT count(*) FROM e WHERE action = 'PRINT'),
    'exports_pdf',        (SELECT count(*) FROM e WHERE action = 'EXPORT' AND (metadata->>'format') ILIKE 'pdf'),
    'exports_excel',      (SELECT count(*) FROM e WHERE action = 'EXPORT' AND (metadata->>'format') ILIKE ANY (ARRAY['xlsx','excel','csv'])),
    'validations',        (SELECT count(*) FROM e WHERE action IN ('VALIDATION','APPROBATION')),
    'annulations',        (SELECT count(*) FROM e WHERE action = 'ANNULATION'),
    'system_errors',      (SELECT count(*) FROM e WHERE status = 'error'),
    'security_alerts',    (SELECT count(*) FROM public.security_alerts WHERE acknowledged_at IS NULL)
  );
$$;

REVOKE ALL ON FUNCTION public.audit_stats_v2() FROM public;
GRANT EXECUTE ON FUNCTION public.audit_stats_v2() TO authenticated;

-- 5. Enable realtime for live dashboard
DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.audit_events;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  ALTER PUBLICATION supabase_realtime ADD TABLE public.security_alerts;
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
