
CREATE INDEX IF NOT EXISTS idx_notifications_date_desc ON public.notifications (date_notification DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_lu ON public.notifications (lu) WHERE lu = false;
CREATE INDEX IF NOT EXISTS idx_commandes_created_at ON public.commandes (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_commandes_date_commande ON public.commandes (date_commande DESC);
CREATE INDEX IF NOT EXISTS idx_commandes_client_id ON public.commandes (client_id);
CREATE INDEX IF NOT EXISTS idx_commandes_statut ON public.commandes (statut);
CREATE INDEX IF NOT EXISTS idx_commande_lignes_commande ON public.commande_lignes (commande_id);
CREATE INDEX IF NOT EXISTS idx_commande_lignes_produit ON public.commande_lignes (produit_id);
CREATE INDEX IF NOT EXISTS idx_factures_commande_id ON public.factures (commande_id);
CREATE INDEX IF NOT EXISTS idx_factures_client_id ON public.factures (client_id);
CREATE INDEX IF NOT EXISTS idx_factures_date ON public.factures (date_facture DESC);
CREATE INDEX IF NOT EXISTS idx_paiements_facture_id ON public.paiements (facture_id);
CREATE INDEX IF NOT EXISTS idx_paiements_date ON public.paiements (date_paiement DESC);
CREATE INDEX IF NOT EXISTS idx_clients_solde ON public.clients (solde DESC);
CREATE INDEX IF NOT EXISTS idx_clients_nom ON public.clients (nom);
CREATE INDEX IF NOT EXISTS idx_clients_representant ON public.clients (representant);
CREATE INDEX IF NOT EXISTS idx_clients_actif_created ON public.clients (actif, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_produits_actif_niveau ON public.produits (actif, niveau_ordre, titre);
CREATE INDEX IF NOT EXISTS idx_produits_actif_created ON public.produits (actif, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_produits_reference ON public.produits (reference);
CREATE INDEX IF NOT EXISTS idx_produits_isbn ON public.produits (isbn);
CREATE INDEX IF NOT EXISTS idx_stock_mouvements_produit_date ON public.stock_mouvements (produit_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_stock_mouvements_depot ON public.stock_mouvements (depot_id);
CREATE INDEX IF NOT EXISTS idx_stocks_depots_produit ON public.stocks_depots (produit_id);
CREATE INDEX IF NOT EXISTS idx_stocks_depots_depot ON public.stocks_depots (depot_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON public.audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_rbac_role_permissions_role ON public.rbac_role_permissions (role_id);
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id ON public.user_roles (user_id);
CREATE INDEX IF NOT EXISTS idx_retour_lignes_produit ON public.retour_lignes (produit_id);
CREATE INDEX IF NOT EXISTS idx_retour_lignes_retour ON public.retour_lignes (retour_id);
CREATE INDEX IF NOT EXISTS idx_retours_client ON public.retours (client_id);
CREATE INDEX IF NOT EXISTS idx_retours_date ON public.retours (date_retour DESC);

ANALYZE public.clients;
ANALYZE public.produits;
ANALYZE public.commandes;
ANALYZE public.factures;
ANALYZE public.paiements;
ANALYZE public.notifications;
