
INSERT INTO public.rbac_permissions (code, module, action, libelle) VALUES
('absences.creer','absences','creer','Créer une absence'),
('absences.modifier','absences','modifier','Modifier une absence'),
('absences.supprimer','absences','supprimer','Supprimer une absence'),
('achats.imprimer','achats','imprimer','Imprimer un achat'),
('achats.payer','achats','payer','Payer un achat'),
('achats.receptionner','achats','receptionner','Réceptionner un achat'),
('alertes_stock.voir','alertes_stock','voir','Voir les alertes de stock (dédiée)'),
('audit.exporter','audit','exporter','Exporter le journal d''audit'),
('audit.recalculer_soldes','audit','recalculer_soldes','Recalculer les soldes clients globaux'),
('backup.creer','backup','creer','Lancer une sauvegarde'),
('balance.exporter_excel','balance','exporter_excel','Exporter la balance'),
('bi_analytics.exporter_excel','bi_analytics','exporter_excel','Exporter les analyses BI en Excel'),
('bons_livraison.creer','bons_livraison','creer','Créer un bon de livraison'),
('bons_livraison.imprimer','bons_livraison','imprimer','Imprimer un BL'),
('bons_livraison.telecharger_pdf','bons_livraison','telecharger_pdf','Télécharger le PDF d''un BL'),
('clients.archiver','clients','archiver','Archiver un client'),
('clients.bloquer','clients','bloquer','Bloquer/débloquer un client'),
('clients.exporter_excel','clients','exporter_excel','Exporter les clients en Excel'),
('clients.voir_ca','clients','voir_ca','Voir le chiffre d''affaires client'),
('clients.voir_historique','clients','voir_historique','Voir l''historique d''un client'),
('clients.voir_stats','clients','voir_stats','Voir les statistiques client'),
('colisage.deverrouiller','colisage','deverrouiller','Déverrouiller un colisage'),
('colisage.imprimer_etiquettes','colisage','imprimer_etiquettes','Imprimer les étiquettes de colis'),
('colisage.modifier','colisage','modifier','Modifier un colisage'),
('colisage_responsables.voir','colisage_responsables','voir','Gérer les responsables colisage'),
('commandes.annuler','commandes','annuler','Annuler une commande'),
('commandes.convertir_en_bl','commandes','convertir_en_bl','Convertir une commande en bon de livraison'),
('commandes.dupliquer','commandes','dupliquer','Dupliquer une commande'),
('commandes.exporter_excel','commandes','exporter_excel','Exporter la liste des commandes'),
('commandes.generer_facture','commandes','generer_facture','Générer une facture depuis une commande'),
('commandes.generer_proforma','commandes','generer_proforma','Générer une proforma depuis une commande'),
('commandes.imprimer','commandes','imprimer','Imprimer une commande'),
('commandes.soumettre','commandes','soumettre','Soumettre une commande pour validation'),
('commandes.telecharger_pdf','commandes','telecharger_pdf','Télécharger le PDF d''une commande'),
('commandes.voir_prix','commandes','voir_prix','Voir les prix dans une commande'),
('comptabilite.exporter_excel','comptabilite','exporter_excel','Exporter des données comptables en Excel'),
('comptabilite.exporter_pdf','comptabilite','exporter_pdf','Exporter des données comptables en PDF'),
('conges.approuver','conges','approuver','Approuver un congé'),
('conges.creer','conges','creer','Créer un congé'),
('conges.modifier','conges','modifier','Modifier un congé'),
('conges.rejeter','conges','rejeter','Rejeter un congé'),
('contrats.creer','contrats','creer','Créer un contrat'),
('contrats.imprimer','contrats','imprimer','Imprimer un contrat'),
('contrats.modifier','contrats','modifier','Modifier un contrat'),
('contrats.supprimer','contrats','supprimer','Supprimer un contrat'),
('couts_logistiques.creer','couts_logistiques','creer','Saisir des coûts logistiques'),
('couts_logistiques.exporter_pdf','couts_logistiques','exporter_pdf','Exporter les coûts logistiques'),
('couts_logistiques.valider','couts_logistiques','valider','Valider des coûts logistiques'),
('dashboard_direction.voir_ca','dashboard_direction','voir_ca','Voir le CA sur le tableau de bord direction'),
('dashboard_direction.voir_marges','dashboard_direction','voir_marges','Voir les marges sur le tableau de bord direction'),
('departements.creer','departements','creer','Créer un département'),
('departements.modifier','departements','modifier','Modifier un département'),
('departements.supprimer','departements','supprimer','Supprimer un département'),
('depots.creer','depots','creer','Créer un dépôt'),
('depots.definir_principal','depots','definir_principal','Définir le dépôt principal'),
('depots.modifier','depots','modifier','Modifier un dépôt'),
('documents.telecharger','documents','telecharger','Télécharger un document'),
('ecritures_comptables.creer','ecritures_comptables','creer','Créer une écriture'),
('ecritures_comptables.modifier','ecritures_comptables','modifier','Modifier une écriture'),
('ecritures_comptables.supprimer','ecritures_comptables','supprimer','Supprimer une écriture'),
('employes.creer','employes','creer','Créer un employé'),
('employes.creer_compte','employes','creer_compte','Créer un compte utilisateur pour un employé'),
('employes.exporter_excel','employes','exporter_excel','Exporter les employés'),
('employes.imprimer_fiche','employes','imprimer_fiche','Imprimer la fiche employé'),
('employes.modifier','employes','modifier','Modifier un employé'),
('employes.renumeroter','employes','renumeroter','Renuméroter les matricules'),
('employes.restaurer','employes','restaurer','Restaurer un employé archivé'),
('etat_compte_clients.exporter_pdf','etat_compte_clients','exporter_pdf','Exporter l''état de compte en PDF'),
('etat_compte_clients.recalculer','etat_compte_clients','recalculer','Recalculer le solde d''un client'),
('evaluations.creer','evaluations','creer','Créer une évaluation'),
('evaluations.modifier','evaluations','modifier','Modifier une évaluation'),
('evaluations.supprimer','evaluations','supprimer','Supprimer une évaluation'),
('exercices.cloturer','exercices','cloturer','Clôturer un exercice'),
('exercices.modifier','exercices','modifier','Modifier un exercice'),
('expeditions.creer','expeditions','creer','Créer une expédition'),
('factures.annuler','factures','annuler','Annuler une facture'),
('factures.exporter_excel','factures','exporter_excel','Exporter les factures en Excel'),
('factures.exporter_pdf','factures','exporter_pdf','Exporter les factures en PDF'),
('factures.imprimer','factures','imprimer','Imprimer une facture'),
('factures.soumettre_fne','factures','soumettre_fne','Soumettre une facture au FNE'),
('factures.voir_prix','factures','voir_prix','Voir les montants d''une facture'),
('fec.generer','fec','generer','Générer le FEC'),
('fec.telecharger','fec','telecharger','Télécharger le FEC'),
('finances.creer','finances','creer','Créer une transaction'),
('finances.exporter_excel','finances','exporter_excel','Exporter les transactions'),
('finances.modifier','finances','modifier','Modifier une transaction'),
('finances.voir_ca','finances','voir_ca','Voir les KPI trésorerie'),
('flotte.creer','flotte','creer','Créer un véhicule / livreur'),
('flotte.modifier','flotte','modifier','Modifier un véhicule / livreur'),
('flotte.supprimer','flotte','supprimer','Supprimer un véhicule / livreur'),
('fne.imprimer','fne','imprimer','Imprimer un document FNE'),
('fne.modifier_parametres','fne','modifier_parametres','Modifier les paramètres FNE'),
('fne.reessayer','fne','reessayer','Réessayer un envoi FNE'),
('fne.rembourser','fne','rembourser','Rembourser via le FNE'),
('fne.soumettre','fne','soumettre','Soumettre une facture au FNE'),
('fne.telecharger_json','fne','telecharger_json','Télécharger le JSON FNE'),
('fonctions.creer','fonctions','creer','Créer une fonction'),
('fonctions.modifier','fonctions','modifier','Modifier une fonction'),
('fonctions.supprimer','fonctions','supprimer','Supprimer une fonction'),
('grand_livre.exporter_excel','grand_livre','exporter_excel','Exporter le grand livre'),
('incidents.creer','incidents','creer','Créer un incident'),
('incidents.imprimer','incidents','imprimer','Imprimer un incident'),
('incidents.modifier','incidents','modifier','Modifier un incident'),
('inventaires.exporter_excel','inventaires','exporter_excel','Exporter un inventaire en Excel'),
('inventaires.regulariser','inventaires','regulariser','Régulariser un inventaire'),
('livraisons.avancer_etape','livraisons','avancer_etape','Faire avancer une étape de livraison'),
('livraisons.avancer_masse','livraisons','avancer_masse','Faire avancer en masse'),
('livraisons.imprimer','livraisons','imprimer','Imprimer une livraison'),
('livraisons.valider_remise','livraisons','valider_remise','Valider une remise de livraison'),
('missions.creer','missions','creer','Créer une mission'),
('missions.modifier','missions','modifier','Modifier une mission'),
('missions.supprimer','missions','supprimer','Supprimer une mission'),
('modeles_documents.creer','modeles_documents','creer','Créer un modèle'),
('modeles_documents.imprimer','modeles_documents','imprimer','Aperçu / impression modèle'),
('modeles_documents.modifier','modeles_documents','modifier','Modifier un modèle'),
('notifications.exporter_historique','notifications','exporter_historique','Exporter l''historique'),
('notifications.generer','notifications','generer','Générer des notifications'),
('notifications.marquer_lue','notifications','marquer_lue','Marquer une notification comme lue'),
('notifications.purger','notifications','purger','Purger les notifications'),
('notifications.supprimer','notifications','supprimer','Supprimer une notification'),
('paie.creer_bulletin','paie','creer_bulletin','Créer un bulletin'),
('paie.declarer_cnps','paie','declarer_cnps','Déclarer la CNPS'),
('paie.declarer_fdfp','paie','declarer_fdfp','Déclarer le FDFP'),
('paie.declarer_its','paie','declarer_its','Déclarer l''ITS'),
('paie.imprimer_bulletin','paie','imprimer_bulletin','Imprimer un bulletin'),
('paie.modifier_bulletin','paie','modifier_bulletin','Modifier un bulletin'),
('paie.supprimer_bulletin','paie','supprimer_bulletin','Supprimer un bulletin'),
('paie.telecharger_declaration','paie','telecharger_declaration','Télécharger une déclaration'),
('paie_rubriques.creer','paie_rubriques','creer','Créer une rubrique de paie'),
('paie_rubriques.modifier','paie_rubriques','modifier','Modifier une rubrique de paie'),
('paie_rubriques.supprimer','paie_rubriques','supprimer','Supprimer une rubrique de paie'),
('paiements.exporter_excel','paiements','exporter_excel','Exporter les paiements'),
('paiements.imprimer_recu','paiements','imprimer_recu','Imprimer un reçu de paiement'),
('paiements.rejeter','paiements','rejeter','Rejeter un paiement'),
('paiements.voir_historique_annulations','paiements','voir_historique_annulations','Voir l''historique des annulations'),
('parametres.modifier','parametres','modifier','Modifier les paramètres système'),
('plan_comptable.creer','plan_comptable','creer','Ajouter un compte au plan comptable'),
('plan_comptable.modifier','plan_comptable','modifier','Modifier un compte du plan comptable'),
('produits.archiver','produits','archiver','Archiver un produit'),
('produits.exporter_excel','produits','exporter_excel','Exporter les produits en Excel'),
('produits.imprimer','produits','imprimer','Imprimer la fiche produit'),
('produits.voir_couts','produits','voir_couts','Voir les prix d''achat / coûts'),
('produits.voir_marges','produits','voir_marges','Voir les marges'),
('produits.voir_prix','produits','voir_prix','Voir les prix de vente'),
('proformas.convertir_en_commande','proformas','convertir_en_commande','Convertir une proforma en commande'),
('proformas.imprimer','proformas','imprimer','Imprimer une proforma'),
('proformas.telecharger_pdf','proformas','telecharger_pdf','Télécharger le PDF d''une proforma'),
('rapports.exporter_excel','rapports','exporter_excel','Exporter les rapports en Excel'),
('rapports.exporter_pdf','rapports','exporter_pdf','Exporter les rapports en PDF'),
('rapports.voir_ca','rapports','voir_ca','Voir le CA dans les rapports'),
('rapports.voir_marges','rapports','voir_marges','Voir les marges dans les rapports'),
('retours.creer','retours','creer','Créer un retour'),
('retours.imprimer','retours','imprimer','Imprimer un retour'),
('roles_permissions.voir_audit','roles_permissions','voir_audit','Voir l''audit RBAC'),
('specimens.creer','specimens','creer','Créer un spécimen'),
('specimens.imprimer','specimens','imprimer','Imprimer un spécimen'),
('stock.creer_mouvement','stock','creer_mouvement','Créer un mouvement de stock manuel'),
('stock.exporter_excel','stock','exporter_excel','Exporter le stock en Excel'),
('stock.recalculer','stock','recalculer','Recalculer le stock (global ou produit)'),
('stock.voir_audit','stock','voir_audit','Voir l''audit du stock'),
('stock.voir_mouvements','stock','voir_mouvements','Voir les mouvements d''un produit'),
('tournees.annuler_validation','tournees','annuler_validation','Annuler la validation d''une tournée'),
('tournees.cloturer','tournees','cloturer','Clôturer une tournée'),
('tournees.imprimer','tournees','imprimer','Imprimer une tournée'),
('tournees.refuser_couts','tournees','refuser_couts','Refuser les coûts d''une tournée'),
('tournees.valider_couts','tournees','valider_couts','Valider les coûts d''une tournée'),
('transferts.creer','transferts','creer','Créer un transfert'),
('transferts.executer','transferts','executer','Exécuter un transfert'),
('transferts.imprimer','transferts','imprimer','Imprimer un transfert'),
('transferts.receptionner','transferts','receptionner','Réceptionner un transfert'),
('transferts.telecharger_pdf','transferts','telecharger_pdf','Télécharger le PDF d''un transfert'),
('utilisateurs.activer_desactiver','utilisateurs','activer_desactiver','Activer / désactiver un utilisateur'),
('utilisateurs.assigner_role','utilisateurs','assigner_role','Assigner un rôle'),
('utilisateurs.reset_mfa','utilisateurs','reset_mfa','Réinitialiser le MFA d''un utilisateur'),
('utilisateurs.revoquer_mfa','utilisateurs','revoquer_mfa','Révoquer le MFA d''un utilisateur')
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.rbac_role_permissions (role_id, permission_code, accorde)
SELECT r.role_id, p.code, true
FROM public.rbac_roles r CROSS JOIN public.rbac_permissions p
WHERE r.code = 'super_admin'
ON CONFLICT (role_id, permission_code) DO UPDATE SET accorde = true;
