-- MISE EN PRODUCTION FABS-CI : purge complète des données transactionnelles.
TRUNCATE TABLE
  public.paiement_annulations_audit,
  public.paiements,
  public.fne_logs,
  public.fne_factures,
  public.bons_retour,
  public.retour_lignes,
  public.retours,
  public.factures,
  public.livraison_commande_historique,
  public.livraisons_commande,
  public.livraisons,
  public.expeditions,
  public.livsuivi_historique,
  public.livsuivi_commandes,
  public.livsuivi_tournees,
  public.tournees,
  public.colis_statut_historique,
  public.colisage_modifications_historique,
  public.colis_lignes,
  public.colis,
  public.ordres_colisage,
  public.bons_livraison,
  public.commande_lignes,
  public.commandes,
  public.proforma_lignes,
  public.proformas,
  public.specimen_lignes,
  public.specimens,
  public.achat_lignes,
  public.achats,
  public.inventaire_lignes,
  public.inventaires,
  public.stock_mouvements,
  public.stocks_depots,
  public.ecriture_lignes,
  public.ecritures_comptables,
  public.transactions,
  public.exercice_cloture_journal,
  public.soldes_ouverture_clients,
  public.soldes_ouverture_fournisseurs,
  public.couts_logistiques,
  public.incident_lignes,
  public.incident_alerts,
  public.incidents,
  public.workflow_approvals,
  public.historique_envois,
  public.documents,
  public.notifications,
  public.notifications_purge_log,
  public.audit_events,
  public.audit_logs,
  public.login_history,
  public.perf_query_log,
  public.trigger_execution_log,
  public.client_fidelite_mouvements
RESTART IDENTITY CASCADE;

-- Reset des soldes matérialisés sur clients (colonnes existantes uniquement)
UPDATE public.clients SET solde = 0, solde_points = 0;

ANALYZE;