-- Consolidated FABS-CI ERP schema
CREATE TYPE public.app_role AS ENUM ('super_admin','directeur_general','comptable','directeur_commercial','gestionnaire_stock','responsable_magasinier','secretariat','assistante','service_logistique');

CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger LANGUAGE plpgsql SET search_path=public AS $$
BEGIN NEW.updated_at=now(); RETURN NEW; END $$;

CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,email text,nom_complet text,avatar_url text,actif boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role; ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Profiles readable by authenticated" ON public.profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "Users update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid()=id) WITH CHECK (auth.uid()=id);
CREATE TRIGGER update_profiles_updated_at BEFORE UPDATE ON public.profiles FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,role public.app_role NOT NULL,UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role; ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users read own roles" ON public.user_roles FOR SELECT TO authenticated USING (auth.uid()=user_id);

CREATE OR REPLACE FUNCTION public.has_role(_user_id uuid,_role public.app_role)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=_role) $$;
CREATE OR REPLACE FUNCTION public.has_any_role(_user_id uuid,_roles public.app_role[])
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id AND role=ANY(_roles)) $$;
CREATE OR REPLACE FUNCTION public.is_staff(_user_id uuid)
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=_user_id) $$;

CREATE POLICY "Super admin manage roles" ON public.user_roles FOR ALL TO authenticated USING (public.has_role(auth.uid(),'super_admin')) WITH CHECK (public.has_role(auth.uid(),'super_admin'));

CREATE SEQUENCE IF NOT EXISTS public.produit_ref_seq;
CREATE SEQUENCE IF NOT EXISTS public.commande_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.transaction_ref_seq;
CREATE SEQUENCE IF NOT EXISTS public.achat_ref_seq;
CREATE SEQUENCE IF NOT EXISTS public.employe_ref_seq;
CREATE SEQUENCE IF NOT EXISTS public.factures_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.paiements_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.proformas_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.livraisons_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.retours_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.missions_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.incidents_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.couts_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.colis_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.fne_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.inventaires_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.workflow_ref_seq START 1;
CREATE SEQUENCE IF NOT EXISTS public.ecriture_ref_seq;

CREATE TABLE public.clients (client_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL DEFAULT ('CLI-'||substr(gen_random_uuid()::text,1,8)),nom text NOT NULL,type_client text NOT NULL DEFAULT 'autre',representant text,telephone text,email text,adresse text,ville text,plafond_credit numeric NOT NULL DEFAULT 0,solde numeric NOT NULL DEFAULT 0,notes text,actif boolean NOT NULL DEFAULT true,nif text,regime_fiscal text,contact_principal text,telephone2 text,quartier text,bp text,pays text DEFAULT 'Côte d''Ivoire',remise_habituelle numeric(5,2) DEFAULT 0,mode_paiement text DEFAULT 'comptant',delai_paiement integer DEFAULT 0,categorie text,secteur_activite text,statut text DEFAULT 'actif',motif_blocage text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.produits (produit_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('PRD-'||lpad(nextval('public.produit_ref_seq')::text,5,'0')),titre text NOT NULL,isbn text,categorie text NOT NULL DEFAULT 'manuel',niveau text,matiere text,auteur text,editeur text,prix_vente numeric NOT NULL DEFAULT 0,prix_achat numeric NOT NULL DEFAULT 0,stock integer NOT NULL DEFAULT 0,seuil_alerte integer NOT NULL DEFAULT 10,actif boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.commandes (commande_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL DEFAULT ('CMD-'||lpad(nextval('public.commande_ref_seq')::text,5,'0')),client_id uuid REFERENCES public.clients(client_id) ON DELETE SET NULL,client_nom text,statut text NOT NULL DEFAULT 'brouillon',date_commande date NOT NULL DEFAULT current_date,remise numeric NOT NULL DEFAULT 0,montant_total numeric NOT NULL DEFAULT 0,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.commande_lignes (ligne_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),commande_id uuid NOT NULL REFERENCES public.commandes(commande_id) ON DELETE CASCADE,produit_id uuid REFERENCES public.produits(produit_id) ON DELETE SET NULL,designation text NOT NULL,quantite integer NOT NULL DEFAULT 1,prix_unitaire numeric NOT NULL DEFAULT 0,total_ligne numeric NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.stock_mouvements (mouvement_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),produit_id uuid NOT NULL REFERENCES public.produits(produit_id) ON DELETE CASCADE,type text NOT NULL DEFAULT 'entree',quantite integer NOT NULL DEFAULT 0,stock_resultant integer NOT NULL DEFAULT 0,motif text,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.transactions (transaction_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('TRX-'||lpad(nextval('public.transaction_ref_seq')::text,5,'0')),type text NOT NULL CHECK(type IN('recette','depense')),categorie text NOT NULL DEFAULT 'autre',libelle text NOT NULL,montant numeric NOT NULL DEFAULT 0,date_transaction date NOT NULL DEFAULT current_date,mode_paiement text NOT NULL DEFAULT 'especes',statut text NOT NULL DEFAULT 'valide',notes text,commande_id uuid REFERENCES public.commandes(commande_id) ON DELETE SET NULL,created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.fournisseurs (fournisseur_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),raison_sociale text NOT NULL,contact text,email text,telephone text,adresse text,ville text,actif boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.achats (achat_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('ACH-'||lpad(nextval('public.achat_ref_seq')::text,5,'0')),fournisseur_id uuid REFERENCES public.fournisseurs(fournisseur_id) ON DELETE SET NULL,libelle text NOT NULL,montant numeric NOT NULL DEFAULT 0,statut text NOT NULL DEFAULT 'brouillon' CHECK(statut IN('brouillon','commande','recu','paye','annule')),date_achat date NOT NULL DEFAULT current_date,notes text,created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.employes (employe_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),matricule text NOT NULL UNIQUE DEFAULT ('EMP-'||lpad(nextval('public.employe_ref_seq')::text,5,'0')),nom_complet text NOT NULL,poste text,departement text NOT NULL DEFAULT 'autre',email text,telephone text,date_embauche date NOT NULL DEFAULT current_date,salaire numeric NOT NULL DEFAULT 0,actif boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.conges (conge_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),employe_id uuid NOT NULL REFERENCES public.employes(employe_id) ON DELETE CASCADE,type text NOT NULL DEFAULT 'annuel',date_debut date NOT NULL,date_fin date NOT NULL,motif text,statut text NOT NULL DEFAULT 'en_attente' CHECK(statut IN('en_attente','approuve','refuse')),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.factures (facture_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('FAC-'||lpad(nextval('public.factures_ref_seq')::text,5,'0')),client_id uuid REFERENCES public.clients(client_id) ON DELETE SET NULL,client_nom text,commande_id uuid REFERENCES public.commandes(commande_id) ON DELETE SET NULL,date_facture date NOT NULL DEFAULT current_date,date_echeance date,montant_total numeric NOT NULL DEFAULT 0,montant_paye numeric NOT NULL DEFAULT 0,statut text NOT NULL DEFAULT 'impayee',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.paiements (paiement_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('PAY-'||lpad(nextval('public.paiements_ref_seq')::text,5,'0')),facture_id uuid REFERENCES public.factures(facture_id) ON DELETE SET NULL,client_nom text,date_paiement date NOT NULL DEFAULT current_date,montant numeric NOT NULL DEFAULT 0,mode_paiement text NOT NULL DEFAULT 'especes',statut text NOT NULL DEFAULT 'valide',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.proformas (proforma_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('PRO-'||lpad(nextval('public.proformas_ref_seq')::text,5,'0')),client_id uuid REFERENCES public.clients(client_id) ON DELETE SET NULL,client_nom text,date_proforma date NOT NULL DEFAULT current_date,date_validite date,montant_total numeric NOT NULL DEFAULT 0,statut text NOT NULL DEFAULT 'en_attente',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.proforma_lignes (ligne_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),proforma_id uuid NOT NULL REFERENCES public.proformas(proforma_id) ON DELETE CASCADE,produit_id uuid,designation text NOT NULL,quantite integer NOT NULL DEFAULT 1,prix_unitaire numeric NOT NULL DEFAULT 0,total_ligne numeric NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.livraisons (livraison_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('LIV-'||lpad(nextval('public.livraisons_ref_seq')::text,5,'0')),commande_id uuid REFERENCES public.commandes(commande_id) ON DELETE SET NULL,client_nom text,transporteur text,adresse text,date_livraison date NOT NULL DEFAULT current_date,statut text NOT NULL DEFAULT 'en_preparation',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.retours (retour_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('RET-'||lpad(nextval('public.retours_ref_seq')::text,5,'0')),client_id uuid REFERENCES public.clients(client_id) ON DELETE SET NULL,client_nom text,produit_nom text,quantite integer NOT NULL DEFAULT 1,motif text,montant numeric NOT NULL DEFAULT 0,date_retour date NOT NULL DEFAULT current_date,statut text NOT NULL DEFAULT 'en_attente',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.departements (departement_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),nom text NOT NULL,responsable text,description text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.contrats (contrat_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),employe_id uuid REFERENCES public.employes(employe_id) ON DELETE SET NULL,employe_nom text,type_contrat text NOT NULL DEFAULT 'cdi',date_debut date NOT NULL DEFAULT current_date,date_fin date,salaire numeric NOT NULL DEFAULT 0,statut text NOT NULL DEFAULT 'actif',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.absences (absence_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),employe_id uuid REFERENCES public.employes(employe_id) ON DELETE SET NULL,employe_nom text,type_absence text NOT NULL DEFAULT 'maladie',date_debut date NOT NULL DEFAULT current_date,date_fin date,motif text,statut text NOT NULL DEFAULT 'en_attente',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.missions (mission_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('MIS-'||lpad(nextval('public.missions_ref_seq')::text,5,'0')),employe_id uuid REFERENCES public.employes(employe_id) ON DELETE SET NULL,employe_nom text,destination text,objet text,date_debut date NOT NULL DEFAULT current_date,date_fin date,budget numeric NOT NULL DEFAULT 0,statut text NOT NULL DEFAULT 'planifiee',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.evaluations (evaluation_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),employe_id uuid REFERENCES public.employes(employe_id) ON DELETE SET NULL,employe_nom text,periode text,note numeric NOT NULL DEFAULT 0,commentaire text,date_evaluation date NOT NULL DEFAULT current_date,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.bulletins_paie (bulletin_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),employe_id uuid REFERENCES public.employes(employe_id) ON DELETE SET NULL,employe_nom text,periode text NOT NULL,salaire_brut numeric NOT NULL DEFAULT 0,retenues numeric NOT NULL DEFAULT 0,salaire_net numeric NOT NULL DEFAULT 0,statut text NOT NULL DEFAULT 'genere',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.incidents (incident_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('INC-'||lpad(nextval('public.incidents_ref_seq')::text,5,'0')),type_incident text NOT NULL DEFAULT 'stock',gravite text NOT NULL DEFAULT 'moyenne',description text,date_incident date NOT NULL DEFAULT current_date,statut text NOT NULL DEFAULT 'ouvert',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.vehicules (vehicule_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),immatriculation text NOT NULL,marque text,modele text,type_vehicule text NOT NULL DEFAULT 'camion',kilometrage integer NOT NULL DEFAULT 0,statut text NOT NULL DEFAULT 'disponible',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.couts_logistiques (cout_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('CLO-'||lpad(nextval('public.couts_ref_seq')::text,5,'0')),categorie text NOT NULL DEFAULT 'carburant',libelle text,montant numeric NOT NULL DEFAULT 0,date_cout date NOT NULL DEFAULT current_date,vehicule_id uuid REFERENCES public.vehicules(vehicule_id) ON DELETE SET NULL,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.colis (colis_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('COL-'||lpad(nextval('public.colis_ref_seq')::text,5,'0')),destinataire text,contenu text,poids numeric NOT NULL DEFAULT 0,transporteur text,date_envoi date NOT NULL DEFAULT current_date,statut text NOT NULL DEFAULT 'en_preparation',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.notifications (notification_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),titre text NOT NULL,message text,type_notification text NOT NULL DEFAULT 'info',lu boolean NOT NULL DEFAULT false,date_notification date NOT NULL DEFAULT current_date,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.fne_factures (fne_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('FNE-'||lpad(nextval('public.fne_ref_seq')::text,5,'0')),facture_id uuid REFERENCES public.factures(facture_id) ON DELETE SET NULL,client_nom text,montant numeric NOT NULL DEFAULT 0,date_emission date NOT NULL DEFAULT current_date,statut text NOT NULL DEFAULT 'en_attente',code_dgi text,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.inventaires (inventaire_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('INV-'||lpad(nextval('public.inventaires_ref_seq')::text,5,'0')),produit_nom text,stock_theorique integer NOT NULL DEFAULT 0,stock_compte integer NOT NULL DEFAULT 0,ecart integer NOT NULL DEFAULT 0,date_inventaire date NOT NULL DEFAULT current_date,statut text NOT NULL DEFAULT 'en_cours',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.documents (document_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),titre text NOT NULL,type_document text NOT NULL DEFAULT 'autre',description text,date_document date NOT NULL DEFAULT current_date,statut text NOT NULL DEFAULT 'actif',created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.workflow_approvals (approval_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('WF-'||lpad(nextval('public.workflow_ref_seq')::text,5,'0')),type_demande text NOT NULL DEFAULT 'achat',demandeur text,objet text,montant numeric NOT NULL DEFAULT 0,date_demande date NOT NULL DEFAULT current_date,statut text NOT NULL DEFAULT 'en_attente',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.parametres (parametre_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),cle text NOT NULL UNIQUE,valeur text,description text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.ecritures_comptables (ecriture_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL DEFAULT ('ECR-'||lpad(nextval('public.ecriture_ref_seq')::text,5,'0')),date_ecriture date NOT NULL DEFAULT current_date,journal text NOT NULL DEFAULT 'OD',libelle text NOT NULL,source_type text,source_id uuid,lettrage text,montant_total numeric NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.ecriture_lignes (ligne_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),ecriture_id uuid NOT NULL REFERENCES public.ecritures_comptables(ecriture_id) ON DELETE CASCADE,compte text NOT NULL,compte_libelle text NOT NULL,debit numeric NOT NULL DEFAULT 0,credit numeric NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.document_templates (template_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,label text NOT NULL,description text,config jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.document_template_prefs (user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,active_template_id text NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.audit_logs (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid,user_email text,action text NOT NULL,table_name text NOT NULL,record_id text,old_values jsonb,new_values jsonb,created_at timestamptz NOT NULL DEFAULT now());

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['clients','produits','commandes','commande_lignes','stock_mouvements','transactions','fournisseurs','achats','employes','conges','factures','paiements','proformas','proforma_lignes','livraisons','retours','departements','contrats','absences','missions','evaluations','bulletins_paie','incidents','vehicules','couts_logistiques','colis','notifications','fne_factures','inventaires','documents','workflow_approvals','parametres','ecritures_comptables','ecriture_lignes','document_templates','document_template_prefs','audit_logs'] LOOP EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON public.%I TO authenticated',t); EXECUTE format('GRANT ALL ON public.%I TO service_role',t); EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); END LOOP; END $$;

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['clients','produits','commandes','commande_lignes','stock_mouvements','transactions','fournisseurs','achats','employes','conges','factures','paiements','proformas','proforma_lignes','livraisons','retours','departements','contrats','absences','missions','evaluations','bulletins_paie','incidents','vehicules','couts_logistiques','colis','notifications','fne_factures','inventaires','documents','workflow_approvals','parametres'] LOOP EXECUTE format('CREATE POLICY "staff read %1$s" ON public.%1$I FOR SELECT TO authenticated USING (public.is_staff(auth.uid()))',t); EXECUTE format('CREATE POLICY "staff write %1$s" ON public.%1$I FOR ALL TO authenticated USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()))',t); BEGIN EXECUTE format('CREATE TRIGGER update_%1$s_updated_at BEFORE UPDATE ON public.%1$I FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column()',t); EXCEPTION WHEN duplicate_object THEN NULL; END; END LOOP; END $$;

CREATE POLICY "Finance ecritures" ON public.ecritures_comptables FOR ALL TO authenticated USING (public.has_any_role(auth.uid(),ARRAY['super_admin','directeur_general','comptable']::app_role[])) WITH CHECK (public.has_any_role(auth.uid(),ARRAY['super_admin','directeur_general','comptable']::app_role[]));
CREATE POLICY "Finance ecriture_lignes" ON public.ecriture_lignes FOR ALL TO authenticated USING (public.has_any_role(auth.uid(),ARRAY['super_admin','directeur_general','comptable']::app_role[])) WITH CHECK (public.has_any_role(auth.uid(),ARRAY['super_admin','directeur_general','comptable']::app_role[]));
CREATE POLICY "Own document templates" ON public.document_templates FOR ALL TO authenticated USING (auth.uid()=user_id) WITH CHECK (auth.uid()=user_id);
CREATE POLICY "Own template pref" ON public.document_template_prefs FOR ALL TO authenticated USING (auth.uid()=user_id) WITH CHECK (auth.uid()=user_id);
CREATE POLICY "Audit lisible direction" ON public.audit_logs FOR SELECT TO authenticated USING (public.has_any_role(auth.uid(),ARRAY['super_admin','directeur_general','comptable']::app_role[]));
CREATE POLICY "Audit insertion staff" ON public.audit_logs FOR INSERT TO authenticated WITH CHECK (public.is_staff(auth.uid()));

CREATE INDEX idx_clients_nom ON public.clients(nom); CREATE INDEX idx_clients_type ON public.clients(type_client); CREATE INDEX idx_clients_telephone ON public.clients(telephone); CREATE INDEX idx_clients_statut ON public.clients(statut); CREATE INDEX idx_clients_ville ON public.clients(ville);
CREATE INDEX idx_produits_reference ON public.produits(reference); CREATE INDEX idx_commandes_client ON public.commandes(client_id); CREATE INDEX idx_commande_lignes_commande ON public.commande_lignes(commande_id); CREATE INDEX idx_stock_mouvements_produit ON public.stock_mouvements(produit_id); CREATE INDEX idx_proforma_lignes_proforma_id ON public.proforma_lignes(proforma_id); CREATE INDEX idx_ecriture_lignes_ecriture_id ON public.ecriture_lignes(ecriture_id); CREATE INDEX idx_ecritures_source ON public.ecritures_comptables(source_type,source_id);

CREATE OR REPLACE FUNCTION public.apply_stock_mouvement()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$
DECLARE current_stock integer; new_stock integer;
BEGIN SELECT stock INTO current_stock FROM public.produits WHERE produit_id=NEW.produit_id FOR UPDATE; IF current_stock IS NULL THEN RAISE EXCEPTION 'Produit introuvable'; END IF; IF NEW.type IN('entree','transfert_entree') THEN new_stock:=current_stock+NEW.quantite; ELSIF NEW.type IN('sortie','transfert_sortie') THEN new_stock:=current_stock-NEW.quantite; ELSE new_stock:=NEW.quantite; END IF; IF new_stock<0 THEN new_stock:=0; END IF; UPDATE public.produits SET stock=new_stock,updated_at=now() WHERE produit_id=NEW.produit_id; NEW.stock_resultant:=new_stock; RETURN NEW; END $$;
CREATE TRIGGER trg_apply_stock_mouvement BEFORE INSERT ON public.stock_mouvements FOR EACH ROW EXECUTE FUNCTION public.apply_stock_mouvement();

CREATE TABLE public.categories_produits (categorie_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),nom text NOT NULL,parent_id uuid REFERENCES public.categories_produits(categorie_id) ON DELETE SET NULL,description text,actif boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.fonctions (fonction_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),libelle text NOT NULL,departement_id uuid REFERENCES public.departements(departement_id) ON DELETE SET NULL,description text,actif boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.bons_livraison (bl_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('BL-'||to_char(now(),'YYYYMMDD-HH24MISS')||'-'||substr(gen_random_uuid()::text,1,4)),commande_id uuid REFERENCES public.commandes(commande_id) ON DELETE SET NULL,client_id uuid REFERENCES public.clients(client_id) ON DELETE SET NULL,date_emission date NOT NULL DEFAULT current_date,date_livraison date,statut text NOT NULL DEFAULT 'brouillon',transporteur text,adresse_livraison text,signataire text,notes text,montant_total numeric(14,2) NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.bons_retour (br_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('BR-'||to_char(now(),'YYYYMMDD-HH24MISS')||'-'||substr(gen_random_uuid()::text,1,4)),client_id uuid REFERENCES public.clients(client_id) ON DELETE SET NULL,facture_id uuid REFERENCES public.factures(facture_id) ON DELETE SET NULL,date_retour date NOT NULL DEFAULT current_date,motif text,statut text NOT NULL DEFAULT 'en_attente',montant numeric(14,2) NOT NULL DEFAULT 0,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.ordres_colisage (ordre_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('OC-'||to_char(now(),'YYYYMMDD-HH24MISS')||'-'||substr(gen_random_uuid()::text,1,4)),commande_id uuid REFERENCES public.commandes(commande_id) ON DELETE SET NULL,nb_colis integer NOT NULL DEFAULT 0,poids_total numeric(10,3) NOT NULL DEFAULT 0,dimensions text,statut text NOT NULL DEFAULT 'en_preparation',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.expeditions (expedition_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('EXP-'||to_char(now(),'YYYYMMDD-HH24MISS')||'-'||substr(gen_random_uuid()::text,1,4)),ordre_colisage_id uuid REFERENCES public.ordres_colisage(ordre_id) ON DELETE SET NULL,bl_id uuid REFERENCES public.bons_livraison(bl_id) ON DELETE SET NULL,transporteur text,tracking text,date_depart date,date_arrivee_prevue date,date_arrivee_reelle date,cout numeric(14,2) NOT NULL DEFAULT 0,statut text NOT NULL DEFAULT 'planifiee',notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.historique_envois (envoi_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),canal text NOT NULL,destinataire text NOT NULL,sujet text,contenu text,document_type text,document_id uuid,statut text NOT NULL DEFAULT 'envoye',erreur text,envoye_par uuid REFERENCES auth.users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.fne_logs (log_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),fne_facture_id uuid REFERENCES public.fne_factures(fne_id) ON DELETE CASCADE,action text NOT NULL,payload jsonb,response jsonb,statut text NOT NULL DEFAULT 'en_cours',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.fne_settings (setting_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),cle text NOT NULL UNIQUE,valeur text,description text,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.two_fa_secrets (user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,secret_chiffre text NOT NULL,active boolean NOT NULL DEFAULT false,codes_recuperation text[],created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.workflows_definitions (workflow_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),nom text NOT NULL,entite_type text NOT NULL,description text,etapes jsonb NOT NULL DEFAULT '[]'::jsonb,actif boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.produits ADD COLUMN categorie_id uuid REFERENCES public.categories_produits(categorie_id) ON DELETE SET NULL; ALTER TABLE public.employes ADD COLUMN fonction_id uuid REFERENCES public.fonctions(fonction_id) ON DELETE SET NULL;

CREATE TABLE public.depots (depot_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),code text UNIQUE NOT NULL,nom text NOT NULL,adresse text,responsable text,telephone text,actif boolean NOT NULL DEFAULT true,is_principal boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE UNIQUE INDEX depots_one_principal ON public.depots(is_principal) WHERE is_principal=true;
CREATE TABLE public.stocks_depots (id uuid PRIMARY KEY DEFAULT gen_random_uuid(),produit_id uuid NOT NULL REFERENCES public.produits(produit_id) ON DELETE CASCADE,depot_id uuid NOT NULL REFERENCES public.depots(depot_id) ON DELETE CASCADE,quantite integer NOT NULL DEFAULT 0,seuil_alerte integer NOT NULL DEFAULT 0,updated_at timestamptz NOT NULL DEFAULT now(),UNIQUE(produit_id,depot_id));
CREATE TABLE public.transferts (transfert_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),numero text UNIQUE NOT NULL,depot_source_id uuid NOT NULL REFERENCES public.depots(depot_id),depot_destination_id uuid NOT NULL REFERENCES public.depots(depot_id),statut text NOT NULL DEFAULT 'brouillon' CHECK(statut IN('brouillon','expedie','recu','annule')),date_creation timestamptz NOT NULL DEFAULT now(),date_expedition timestamptz,date_reception timestamptz,transporteur text,motif text,notes text,created_by uuid REFERENCES auth.users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CHECK(depot_source_id<>depot_destination_id));
CREATE TABLE public.transfert_lignes (ligne_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),transfert_id uuid NOT NULL REFERENCES public.transferts(transfert_id) ON DELETE CASCADE,produit_id uuid NOT NULL REFERENCES public.produits(produit_id),quantite integer NOT NULL CHECK(quantite>0),quantite_recue integer NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.stock_mouvements ADD COLUMN depot_id uuid REFERENCES public.depots(depot_id);

CREATE TABLE public.document_settings (user_id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,settings jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());

CREATE TABLE public.specimens (specimen_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text UNIQUE,date_remise date NOT NULL DEFAULT current_date,gestionnaire_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,gestionnaire_nom text,motif text,observations text,client_id uuid REFERENCES public.clients(client_id) ON DELETE SET NULL,beneficiaire_nom text,telephone text,etablissement text,ville text,adresse text,statut text NOT NULL DEFAULT 'brouillon',montant_theorique numeric NOT NULL DEFAULT 0,total_quantite integer NOT NULL DEFAULT 0,created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),CONSTRAINT specimens_statut_chk CHECK(statut IN('brouillon','validee','annulee')),CONSTRAINT specimens_beneficiaire_chk CHECK(client_id IS NOT NULL OR (beneficiaire_nom IS NOT NULL AND length(trim(beneficiaire_nom))>0)));
CREATE TABLE public.specimen_lignes (ligne_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),specimen_id uuid NOT NULL REFERENCES public.specimens(specimen_id) ON DELETE CASCADE,produit_id uuid NOT NULL REFERENCES public.produits(produit_id) ON DELETE RESTRICT,reference_produit text,designation text NOT NULL,quantite integer NOT NULL CHECK(quantite>0),prix_unitaire_theorique numeric NOT NULL DEFAULT 0,total_ligne numeric NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());

ALTER TABLE public.achats ADD COLUMN date_commande date,ADD COLUMN date_reception date,ADD COLUMN date_paiement date,ADD COLUMN fournisseur_nom text,ADD COLUMN total_quantite integer NOT NULL DEFAULT 0,ADD COLUMN created_by_nom text;
CREATE TABLE public.achat_lignes (ligne_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),achat_id uuid NOT NULL REFERENCES public.achats(achat_id) ON DELETE CASCADE,produit_id uuid NOT NULL REFERENCES public.produits(produit_id),designation text NOT NULL,quantite integer NOT NULL CHECK(quantite>0),prix_unitaire numeric NOT NULL DEFAULT 0,total_ligne numeric NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.incidents ADD COLUMN IF NOT EXISTS reporter_nom text,ADD COLUMN IF NOT EXISTS depot_id uuid REFERENCES public.depots(depot_id) ON DELETE SET NULL,ADD COLUMN IF NOT EXISTS produit_id uuid REFERENCES public.produits(produit_id) ON DELETE SET NULL,ADD COLUMN IF NOT EXISTS impact_stock integer NOT NULL DEFAULT 0,ADD COLUMN IF NOT EXISTS cout_estime numeric NOT NULL DEFAULT 0,ADD COLUMN IF NOT EXISTS resolution text,ADD COLUMN IF NOT EXISTS resolved_at timestamptz;
CREATE TABLE public.incident_lignes (ligne_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),incident_id uuid NOT NULL REFERENCES public.incidents(incident_id) ON DELETE CASCADE,produit_id uuid REFERENCES public.produits(produit_id) ON DELETE SET NULL,designation text NOT NULL,quantite integer NOT NULL DEFAULT 0,impact_stock integer NOT NULL DEFAULT 0,commentaire text,created_at timestamptz NOT NULL DEFAULT now());
DROP TABLE public.inventaires CASCADE;
CREATE TABLE public.inventaires (inventaire_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),reference text NOT NULL UNIQUE DEFAULT ('INV-'||to_char(now(),'YYYYMMDD-HH24MISS')||'-'||substr(gen_random_uuid()::text,1,4)),depot_id uuid REFERENCES public.depots(depot_id) ON DELETE SET NULL,type_inventaire text NOT NULL DEFAULT 'tournant' CHECK(type_inventaire IN('general','tournant','controle')),statut text NOT NULL DEFAULT 'brouillon' CHECK(statut IN('brouillon','en_cours','valide','annule')),date_inventaire date NOT NULL DEFAULT current_date,responsable_id uuid REFERENCES auth.users(id),responsable_nom text,nb_produits integer NOT NULL DEFAULT 0,total_ecart integer NOT NULL DEFAULT 0,notes text,created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE public.inventaire_lignes (ligne_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),inventaire_id uuid NOT NULL REFERENCES public.inventaires(inventaire_id) ON DELETE CASCADE,produit_id uuid NOT NULL REFERENCES public.produits(produit_id),reference_produit text,designation text NOT NULL,stock_theorique integer NOT NULL DEFAULT 0,stock_compte integer,ecart integer NOT NULL DEFAULT 0,commentaire text,created_at timestamptz NOT NULL DEFAULT now());
ALTER TABLE public.retours ADD COLUMN IF NOT EXISTS client_id uuid REFERENCES public.clients(client_id) ON DELETE SET NULL,ADD COLUMN IF NOT EXISTS facture_id uuid REFERENCES public.factures(facture_id) ON DELETE SET NULL,ADD COLUMN IF NOT EXISTS commande_id uuid REFERENCES public.commandes(commande_id) ON DELETE SET NULL,ADD COLUMN IF NOT EXISTS depot_id uuid REFERENCES public.depots(depot_id) ON DELETE SET NULL,ADD COLUMN IF NOT EXISTS type_retour text NOT NULL DEFAULT 'client',ADD COLUMN IF NOT EXISTS responsable_nom text,ADD COLUMN IF NOT EXISTS total_quantite integer NOT NULL DEFAULT 0;
CREATE TABLE public.retour_lignes (ligne_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),retour_id uuid NOT NULL REFERENCES public.retours(retour_id) ON DELETE CASCADE,produit_id uuid REFERENCES public.produits(produit_id) ON DELETE SET NULL,designation text NOT NULL,quantite integer NOT NULL CHECK(quantite>0),prix_unitaire numeric NOT NULL DEFAULT 0,total_ligne numeric NOT NULL DEFAULT 0,remise_en_stock boolean NOT NULL DEFAULT true,created_at timestamptz NOT NULL DEFAULT now());

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['categories_produits','fonctions','bons_livraison','bons_retour','ordres_colisage','expeditions','historique_envois','fne_logs','fne_settings','two_fa_secrets','workflows_definitions','depots','stocks_depots','transferts','transfert_lignes','document_settings','specimens','specimen_lignes','achat_lignes','incident_lignes','inventaires','inventaire_lignes','retour_lignes'] LOOP EXECUTE format('GRANT SELECT,INSERT,UPDATE,DELETE ON public.%I TO authenticated',t); EXECUTE format('GRANT ALL ON public.%I TO service_role',t); EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY',t); END LOOP; END $$;

DO $$ DECLARE t text; BEGIN FOREACH t IN ARRAY ARRAY['categories_produits','fonctions','bons_livraison','bons_retour','ordres_colisage','expeditions','historique_envois','fne_logs','depots','stocks_depots','transferts','transfert_lignes','specimens','specimen_lignes','achat_lignes','incident_lignes','inventaires','inventaire_lignes','retour_lignes'] LOOP EXECUTE format('CREATE POLICY "auth read %1$s" ON public.%1$I FOR SELECT TO authenticated USING (true)',t); EXECUTE format('CREATE POLICY "staff write %1$s" ON public.%1$I FOR ALL TO authenticated USING (public.is_staff(auth.uid())) WITH CHECK (public.is_staff(auth.uid()))',t); END LOOP; END $$;
CREATE POLICY "admin fne_settings" ON public.fne_settings FOR ALL TO authenticated USING (public.has_any_role(auth.uid(),ARRAY['super_admin','directeur_general']::app_role[])) WITH CHECK (public.has_any_role(auth.uid(),ARRAY['super_admin','directeur_general']::app_role[]));
CREATE POLICY "own 2fa" ON public.two_fa_secrets FOR ALL TO authenticated USING (user_id=auth.uid()) WITH CHECK (user_id=auth.uid());
CREATE POLICY "admin workflows_def" ON public.workflows_definitions FOR ALL TO authenticated USING (public.has_any_role(auth.uid(),ARRAY['super_admin','directeur_general']::app_role[])) WITH CHECK (public.has_any_role(auth.uid(),ARRAY['super_admin','directeur_general']::app_role[]));
CREATE POLICY "own document_settings" ON public.document_settings FOR ALL TO authenticated USING (user_id=auth.uid()) WITH CHECK (user_id=auth.uid());

INSERT INTO public.depots(code,nom,is_principal) VALUES('DEP-PRINCIPAL','Dépôt Principal',true);
INSERT INTO public.stocks_depots(produit_id,depot_id,quantite) SELECT p.produit_id,d.depot_id,COALESCE(p.stock,0) FROM public.produits p CROSS JOIN public.depots d WHERE d.is_principal=true;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.profiles(id,email,nom_complet) VALUES(NEW.id,NEW.email,NEW.raw_user_meta_data->>'nom_complet') ON CONFLICT(id) DO NOTHING; RETURN NEW; END $$;
CREATE OR REPLACE FUNCTION public.bootstrap_first_super_admin()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN IF NOT EXISTS(SELECT 1 FROM public.user_roles WHERE role='super_admin') THEN NEW.role:='super_admin'; END IF; RETURN NEW; END $$;

CREATE OR REPLACE FUNCTION public.set_specimen_reference()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_seq integer; BEGIN IF NEW.reference IS NOT NULL AND length(trim(NEW.reference))>0 THEN RETURN NEW; END IF; SELECT count(*)+1 INTO v_seq FROM public.specimens WHERE date_remise=NEW.date_remise; NEW.reference:='SPC-'||to_char(NEW.date_remise,'YYYYMMDD')||'-'||lpad(v_seq::text,4,'0'); RETURN NEW; END $$;
CREATE TRIGGER trg_specimens_reference BEFORE INSERT ON public.specimens FOR EACH ROW EXECUTE FUNCTION public.set_specimen_reference();
CREATE OR REPLACE FUNCTION public.refresh_specimen_totaux(_specimen_id uuid)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN UPDATE public.specimens s SET montant_theorique=COALESCE((SELECT sum(total_ligne) FROM public.specimen_lignes WHERE specimen_id=_specimen_id),0),total_quantite=COALESCE((SELECT sum(quantite) FROM public.specimen_lignes WHERE specimen_id=_specimen_id),0),updated_at=now() WHERE s.specimen_id=_specimen_id; END $$;
CREATE OR REPLACE FUNCTION public.trg_specimen_lignes_totaux()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE v_id uuid; BEGIN IF TG_OP='DELETE' THEN v_id:=OLD.specimen_id; ELSE v_id:=NEW.specimen_id; END IF; PERFORM public.refresh_specimen_totaux(v_id); RETURN NULL; END $$;
CREATE TRIGGER trg_specimen_lignes_totaux_ins AFTER INSERT OR UPDATE OR DELETE ON public.specimen_lignes FOR EACH ROW EXECUTE FUNCTION public.trg_specimen_lignes_totaux();
